; opcache хранит в оперативной памяти предварительно скомпилированный байткод скриптов
[opcache]
opcache.enable=0
; Отключает opcache для CLI, чтобы сэкономить память при выполнении скриптов из командной строки.
opcache.enable_cli=0
; Выделяет 64 МБ для кэша байт-кода. Для сервера с 2 ГБ RAM это разумный компромисс (можно увеличить до 128 МБ, если другие сервисы оптимизированы).
opcache.memory_consumption=64
; Выделяет 8 МБ для кэширования строк. Подходит для большинства приложений.
opcache.interned_strings_buffer=8
; Ограничивает количество кэшируемых файлов. Для большинства приложений 4000 достаточно (можно увеличить до 10000, если у вас много PHP-файлов).
opcache.max_accelerated_files=4000
; Интервал проверки изменения файлов. (При opcache.validate_timestamps=0, Проверка файлов отключена полностью. При обновлении кода OPcache необходимо очищать вручную.)
opcache.revalidate_freq=0
; Выключает проверку изменений PHP файлов. При необходимости сбросить кеш (редактирование конфигов) можно вызвать `opcache_reset()`.
opcache.validate_timestamps=0
; Сохранение комментариев (включая PHPDoc-аннотации) в кэше байт-кода. Множество современных PHP-фреймворков и библиотек (например, Symfony, Doctrine, API Platform, PHPUnit) активно используют аннотации (сейчас часто называемые атрибутами в новых версиях PHP), прописанные прямо в комментариях к классам и методам.
opcache.save_comments=1
