[xdebug]
;zend_extension=xdebug ; Включается в Dockerfile с помощью `docker-php-ext-enable xdebug`
xdebug.client_host=host.docker.internal
;xdebug.client_host=172.17.0.1
xdebug.client_port=9003
xdebug.discover_client_host=0
xdebug.idekey=PHPSTORM
; Режим работы передаётся через переменную окружения контейнера `XDEBUG_MODE=develop,debug`
; xdebug.mode=develop: включает помощники для разработки, такие как улучшенная функция var_dump(), улучшенные сообщения об ошибках и другие функции для разработки. на `xdebug.start_with_request` не влияет.
; xdebug.mode=coverage: Включает анализ покрытия кода (например, для PHPUnit).
; xdebug.mode=debug: Включает пошаговую отладку. (при этом по умолчанию xdebug.start_with_request=trigger)
; xdebug.mode=profile: Включает профилирование производительности.
; xdebug.mode=trace: Включает трассировку функций.
; xdebug.mode=develop,debug
; xdebug.start_with_request=trigger ; yes - всегда, trigger - только по триггеру (например, ?XDEBUG_SESSION=start)
;xdebug.log=/var/log/xdebug/xdebug.log
;xdebug.log_level=10
;xdebug.output_dir=/var/log/xdebug/
