[supervisord]
;Start Supervisor in the foreground instead of daemonizing (это ключевой момент для Docker).
nodaemon=true
; Supervisord должен стартовать от root, чтобы мог управлять дочерними процессами (воркеры ниже запускаются от www-data).
user = root
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisor/supervisord.pid

[program:php-fpm]
command=php-fpm
stdout_logfile=/var/log/supervisor/php-fpm-out.log
;stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/php-fpm-err.log
;stderr_logfile_maxbytes=0

; Пример конфига Yii2
; https://www.yiiframework.com/extension/yiisoft/yii2-queue/doc/guide/2.0/ru/worker

[program:yii-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /app/yii queue/listen --verbose=1 --color=0
autostart=true
autorestart=true
user=www-data
numprocs=4
;redirect_stderr=true
stderr_logfile=/var/log/supervisor/yii-queue-worker-err.log
stdout_logfile=/var/log/supervisor/yii-queue-worker-out.log

; Этот пример указывает, что Supervisor должен запустить 4 воркера queue/listen, наблюдать за ними,
; и автоматически перезапускать их если они будут падать. Весь вывод будет писаться в лог.
; Запуск воркера в режиме демона командой queue/listen поддерживают драйвера File, Db, Redis, RabbitMQ, Beanstalk, Gearman.


; Пример запуска задач по событиям (периодически в варианте ниже)
;[eventlistener:cleanup-daily]
;command=/usr/local/bin/php /app/yii cleanup-logs/cleanup 30
;events=TICK_86400
;user=www-data
;stdout_logfile=/var/log/supervisor/cleanup-daily-out.log
;stderr_logfile=/var/log/supervisor/cleanup-daily-err.log
